### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by Unisay** [stanch/reftree#5]
http://www.scala-lang.org/news/2.12.0

**Comment by stanch** [comment]
Let’s see... here is the current status:
* [ ] uk.co.turingatemyhamster:gv-core_2.12:0.3.2 (https://github.com/drdozer/graphviz-s/issues/15)
* [ ] org.stanch:zipper_2.12:0.3.1 — I will publish this one soon
* [ ] de.sciss:fingertree_2.12:1.5.2 (https://github.com/Sciss/FingerTree/issues/6)
* [ ] com.chuusai:shapeless_2.12:2.2.5 — I think I need to upgrade to the `2.3.X` series. Last time I tried it something was not working, but I don’t remember what exactly. Contributions are welcome :)
* [ ] com.sksamuel.scrimage:scrimage-core_2.12:2.1.7 (https://github.com/sksamuel/scrimage/issues/121)

**Comment by rklaehn** [comment]
I know that just saying :+1: is not very helpful, but...

 :+1:

**Comment by stanch** [comment]
I am happy to cross-build as soon as drdozer/graphviz-s#15 is fixed :) Another option is to fork that repo and publish myself. I will leave a comment there.
